// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnhtiAYgXtcRWJ28t2BVUfKHLDQssO6c',
    appId: '1:999348652604:android:8a9f28024b66d8804e5139',
    messagingSenderId: '999348652604',
    projectId: 'sih1-362d2',
    storageBucket: 'sih1-362d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtNzDTylT_4VYRfc0js3a3upa1pWhjDo',
    appId: '1:999348652604:ios:ab7fbc2776b953354e5139',
    messagingSenderId: '999348652604',
    projectId: 'sih1-362d2',
    storageBucket: 'sih1-362d2.appspot.com',
    iosBundleId: 'com.example.shesafe',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hAa2VuBDs4w2mAFwbXMqoyZLIaMb8RM',
    appId: '1:999348652604:web:43b784ef9722e0494e5139',
    messagingSenderId: '999348652604',
    projectId: 'sih1-362d2',
    authDomain: 'sih1-362d2.firebaseapp.com',
    storageBucket: 'sih1-362d2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtNzDTylT_4VYRfc0js3a3upa1pWhjDo',
    appId: '1:999348652604:ios:ab7fbc2776b953354e5139',
    messagingSenderId: '999348652604',
    projectId: 'sih1-362d2',
    storageBucket: 'sih1-362d2.appspot.com',
    iosBundleId: 'com.example.shesafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1hAa2VuBDs4w2mAFwbXMqoyZLIaMb8RM',
    appId: '1:999348652604:web:c800098669076e1c4e5139',
    messagingSenderId: '999348652604',
    projectId: 'sih1-362d2',
    authDomain: 'sih1-362d2.firebaseapp.com',
    storageBucket: 'sih1-362d2.appspot.com',
  );

}